rulelist = [
    {
        "name": "schema_other",
        "maps": {
            "CLASSIC_BAG": "s1011105",
            "TRAINING_BAG": "s1011105",
            "TRAINING_OTHERS": "s1011107",
            "CLASSIC_GLOVES": "s1011111",
            "TRAINING_GLOVES": "s1011111",
            "CLASSIC_SCARF": "s1011116",
            "CLASSIC_CAP": "s1011126",
            "RUNNING_CAP": "s1011126",
            "TRAINING_CAP": "s1011126",
            "TRAINING_BOTTLE": "s1011128",
            "CLASSIC_SOCKS": "s1011129",
            "RUNNING_SOCKS": "s1011129",
            "TRAINING_SOCKS": "s1011129",
            "CLASSIC_VEST": "s101060701",
            "RUNNING_PANTS": "s101060101",
            "CLASSIC_TIGHTS": "s101060101",
            "RUNNING_TIGHTS": "s101060101",
            "TRAINING_PANTS": "s101060101",
            "TRAINING_SHORTS": "s101060101",
            "TRAINING_TIGHTS": "s101060101",
            "RUNNING_TEE/LS": "s101060103",
            "RUNNING_TEE/SS": "s101060103",
            "TRAINING_TANK": "s101060103",
            "TRAINING_TEE/LS": "s101060103",
            "TRAINING_TEE/SS": "s101060103",
            "CLASSIC_VEST/PAD": "s101060702",
            "CLASSIC_VEST/DOWN": "s101060703",
            "CLASSIC_POLO/SS": "s1010603",
            "TRAINING_POLO/SS": "s1010603",
            "CLASSIC_TANK": "s101061001",
            "RUNNING_TANK": "s101061001",
            "CLASSIC_TEE/LS": "s1010604",
            "CLASSIC_TEE/SS": "s1010604",
            "CLASSIC_SKIRTS": "s101061301",
            "CLASSIC_DRESS": "s101061301",
            "CLASSIC_JKT/PAD": "s1010609",
            "RUNNING_JKT/PAD": "s1010609",
            "TRAINING_JKT/PAD": "s1010609",
            "CLASSIC_BRA": "s101061004",
            "RUNNING_BRA": "s101061004",
            "TRAINING_BRA": "s101061004",
            "CLASSIC_JACKET": "s1010611",
            "CLASSIC_JKT/WINDBREAKER": "s1010611",
            "RUNNING_JACKET": "s1010611",
            "TRAINING_JACKET": "s1010611",
            "TRAINING_JKT/WINDBREAKER": "s1010611",
            "CLASSIC_BODYSUIT": "s1010614",
            "CLASSIC_SUITS": "s1010614",
            "CLASSIC_Hoodie": "s1010615",
            "CLASSIC_SHIRTS": "s1010615",
            "CLASSIC_SWEATSHIRTS": "s1010615",
            "RUNNING_HOODIE": "s1010615",
            "TRAINING_HOODIE": "s1010615",
            "TRAINING_SWEATSHIRTS": "s1010615",
            "CLASSIC_JKT/DOWN": "s1010616",
            "RUNNING_JKT/DOWN": "s1010616",
            "RUNNING_VEST/DOWN": "s1010616",
            "TRAINING_JKT/DOWN": "s1010616",
            "CLASSIC_PANTS": "s101060602",
            "CLASSIC_SHORTS": "s101060603",
            "RUNNING_SHORTS": "s101060603",
            "RUNNING_BAG": "s1011105",
            "Training_BACKPACK": "s1011105",
            "TRAINING_SHOE BAG": "s1011105",
            "TRAINING_BACKPACK": "s1011105",
            "CLASSIC_BACKPACK": "s1011105",
            "CLASSIC_HAT": "s1011107",
            "TRAINING_TOWEL": "s1011107",
            "RUNNING_HAT": "s1011107",
            "RUNNING_GLOVES": "s1011107",
            "Training_HEADBAND": "s1011107",
            "TRAINING_WRISTBAND": "s1011107",
            "CLASSIC_TOWEL": "s1011107",
            "CLASSIC_Hat": "s1011107",
            "CLASSIC_OTHERS": "s1011107",
            "TRAINING_APPAREL OTHERS": "s1011107",
            "RUNNING_VEST": "s101060701",
            "TRAINING_VEST": "s101060701",
            "CLASSIC_POLO/LS": "s1010603",
            "TRAINING_3/4 PANTS": "s101060101",
            "CLASSIC_3/4 PANTS": "s101060101",
            "TRAINING_SKIRTS": "s101061301",
            "CLASSIC_TRACK TOP": "s1010611",
            "RUNNING_JKT/WINDBREAKER": "s1010611",
            "TRAINING_TRACK TOP": "s1010611",
            "Training_TRACK TOP": "s1010611",
            "Training_SUITS": "s1010614",
            "TRAINING_SUITS": "s1010614",
            "Running_SHIRTS": "s1010615",
            "Training_SHIRTS": "s1010615",
            "TRAINING_SHIRTS": "s1010615",
            "RUNNING_SWEATSHIRTS": "s1010615",
            "TRAINING_VEST/DOWN": "s1010616",
            "Training_CL JOGGER INFANTS": "s101060602",
            "CLASSIC_SHOES": "s1011705"
        }
    },
    {
        "name": "schema_ftw",
        "maps": {
            "BERLIN": "s1011714",
            "VULC": "s1011714",
            "CVS": "s1011714",
            "ARDARA": "s1011716",
            "CLOUDRIDE DMX": "s1011716",
            "Back to Trail": "s1011716",
            "RIDGERIDER": "s1011716",
            "DMX LITE": "s1011716",
            "EVER ROAD": "s1011716",
            "FLEX WALK": "s1011716",
            "LUX WALK": "s1011716",
            "PENNY MOON": "s1011716",
            "ANSWER": "s1011701",
            "KAMIKAZE": "s1011701",
            "QUESTION": "s1011701",
            "SHAQNOSIS": "s1011701",
            "ENERGEN RUN": "s1011704",
            "QUICK CHASE": "s1011704",
            "RUNNER": "s1011704",
            "ASTRORIDE": "s1011704",
            "ZIG": "s1011704",
            "ENERGYLUX DRIFTIUM": "s1011704",
            "LITE 2.0": "s1011704",
            "FLASHFILM": "s1011704",
            "LITE PLUS": "s1011704",
            "FLOATRIDE": "s1011704",
            "FUSIUM RUN": "s1011704",
            "LIQUIFECT": "s1011704",
            "SOLE FURY": "s1011704",
            "CASH FLIP": "s1011708",
            "ADVANCED": "s1011713",
            "DART": "s1011713",
            "ESSENTIAL 2.0": "s1011713",
            "FLEXAGON": "s1011713",
            "FREESTYLE": "s1011713",
            "GURESU": "s1011713",
            "HIIT": "s1011713",
            "LEGACYLIFTER": "s1011713",
            "LIFTER": "s1011713",
            "NANO": "s1011713",
            "NANO X": "s1011713",
            "REAGO": "s1011713",
            "BEATNIK": "s1011707",
            "SANDAL": "s1011707",
            "SLIDE": "s1011708"
        }
    },

    {
        "name": "title-gender",
        "maps": {
            'UNISEX': '男女运动',
            'MEN': '男子运动',
            'JUNIOR': '儿童运动',
            'YOUTH': '儿童运动',
            'WOMEN': '女子运动',
            'BOYS': '男童运动',
            'GIRLS': '女童运动',
            'INFANTS': '婴童运动',
            'KIDS': '儿童运动'
        }
    }, {
        "name": "title_modelname1",
        "maps": {
            "REEBOK ROYAL GLIDE RPLDBL": "GLIDE RPLDBL",
            "REEBOK ROYAL ULTRA": "ULTRA",
            "REEBOK ROYAL TECHQUE T": "TECHQUE T",
            "REEBOK DMX TRAIL SHADOW": "DMX TRAIL SHADOW",
            "REEBOK RUNNER 4.0": "RUNNER 4.0",
            "REEBOK DMX TRAIL HYDREX": "DMX TRAIL HYDREX"
        }
    },
    {
        "name": "title_modelname5",
        "maps": {
            "LM": "莱美",
            "2-1": "防走光"
        }
    },
    {
        "name": "title_product_type",
        "maps": {
            "SHOES - MID (NO-FB)": "中帮",
            "SHOES - MID (NON-FOOTBALL)": "中帮",
            "SHOES - HIGH (NO-FB": "高帮",
            "SHOES - HIGH (NON-FOOTBALL)": "高帮",
            "SHOES - LOW (NO-FB)": "低帮",
            "SHOES - LOW (NON FOOTBALL)": "低帮"
        }
    },
    {
        "name": "title_gender",
        "maps": {
            "UNISEX": "男女运动",
            "MEN": "男子运动",
            "JUNIOR": "儿童运动",
            "YOUTH": "儿童运动",
            "WOMEN": "女子运动",
            "BOYS": "男童运动",
            "GIRLS": "女童运动",
            "INFANTS": "婴童运动",
            "KIDS": "儿童运动"
        }
    }, {
        "name": "title_modelname4",
        "maps": {
            "BERLIN": "帆布鞋",
            "VULC": "帆布鞋",
            "CVS": "帆布鞋",
            "ARDARA": "健步鞋",
            "CLOUDRIDE DMX": "健步鞋",
            "Back to Trail": "健步鞋",
            "RIDGERIDER": "健步鞋",
            "DMX LITE": "健步鞋",
            "EVER ROAD": "健步鞋",
            "FLEX WALK": "健步鞋",
            "LUX WALK": "健步鞋",
            "PENNY MOON": "健步鞋",
            "ANSWER": "篮球鞋",
            "KAMIKAZE": "篮球鞋",
            "QUESTION": "篮球鞋",
            "SHAQNOSIS": "篮球鞋",
            "ENERGEN RUN": "跑步鞋",
            "QUICK CHASE": "跑步鞋",
            "RUNNER": "跑步鞋",
            "ASTRORIDE": "跑步鞋",
            "ZIG": "跑步鞋",
            "ENERGYLUX DRIFTIUM": "跑步鞋",
            "LITE 2.0": "跑步鞋",
            "FLASHFILM": "跑步鞋",
            "LITE PLUS": "跑步鞋",
            "FLOATRIDE": "跑步鞋",
            "FUSIUM RUN": "跑步鞋",
            "LIQUIFECT": "跑步鞋",
            "SOLE FURY": "跑步鞋",
            "CASH FLIP": "拖鞋",
            "ADVANCED": "训练鞋",
            "DART": "训练鞋",
            "ESSENTIAL 2.0": "训练鞋",
            "FLEXAGON": "训练鞋",
            "FREESTYLE": "训练鞋",
            "GURESU": "训练鞋",
            "HIIT": "训练鞋",
            "LEGACYLIFTER": "训练鞋",
            "LIFTER": "训练鞋",
            "NANO": "训练鞋",
            "NANO X": "训练鞋",
            "REAGO": "训练鞋",
            "BEATNIK": "运动拖鞋",
            "SANDAL": "运动拖鞋",
            "SLIDE": "运动拖鞋"
        }
    }, {
        "name": "title_app",
        "maps": {
            "CLASSIC_BAG": "包",
            "CLASSIC_BODYSUIT": "连体衣",
            "CLASSIC_BRA": "文胸内衣",
            "CLASSIC_CAP": "帽子",
            "CLASSIC_DRESS": "连衣裙",
            "CLASSIC_GLOVES": "手套",
            "CLASSIC_Hoodie": "休闲连帽卫衣",
            "CLASSIC_JACKET": "休闲夹克外套",
            "CLASSIC_JKT/DOWN": "羽绒服外套",
            "CLASSIC_JKT/PAD": "棉服外套",
            "CLASSIC_JKT/WINDBREAKER": "休闲户外防风衣外套",
            "CLASSIC_PANTS": "休闲长裤",
            "CLASSIC_POLO/SS": "POLO 短袖T恤",
            "CLASSIC_SCARF": "围脖",
            "CLASSIC_SHIRTS": "休闲上衣",
            "CLASSIC_SHORTS": "休闲短裤",
            "CLASSIC_SKIRTS": "休闲半裙",
            "CLASSIC_SOCKS": "袜子",
            "CLASSIC_SUITS": "套装",
            "CLASSIC_SWEATSHIRTS": "休闲套头衫",
            "CLASSIC_TANK": "运动背心",
            "CLASSIC_TEE/LS": "休闲长袖T恤",
            "CLASSIC_TEE/SS": "休闲短袖T恤",
            "CLASSIC_TIGHTS": "紧身裤打底裤",
            "CLASSIC_VEST": "休闲背心外套",
            "CLASSIC_VEST/DOWN": "休闲羽绒背心外套",
            "CLASSIC_VEST/PAD": "休闲棉背心外套",
            "RUNNING_BRA": "文胸内衣",
            "RUNNING_CAP": "帽子",
            "RUNNING_HOODIE": "休闲连帽卫衣",
            "RUNNING_JACKET": "休闲夹克外套",
            "RUNNING_JKT/DOWN": "羽绒服外套",
            "RUNNING_JKT/PAD": "棉服外套",
            "RUNNING_PANTS": "休闲长裤",
            "RUNNING_SHORTS": "休闲短裤",
            "RUNNING_SOCKS": "袜子",
            "RUNNING_TANK": "运动背心",
            "RUNNING_TEE/LS": "休闲长袖T恤",
            "RUNNING_TEE/SS": "休闲短袖T恤",
            "RUNNING_TIGHTS": "紧身裤打底裤",
            "RUNNING_VEST/DOWN": "休闲羽绒背心外套",
            "TRAINING_BAG": "包",
            "TRAINING_BOTTLE": "水壶",
            "TRAINING_BRA": "文胸内衣",
            "TRAINING_CAP": "帽子",
            "TRAINING_GLOVES": "手套",
            "TRAINING_HOODIE": "休闲连帽卫衣",
            "TRAINING_JACKET": "休闲夹克外套",
            "TRAINING_JKT/DOWN": "羽绒服外套",
            "TRAINING_JKT/PAD": "棉服外套",
            "TRAINING_JKT/WINDBREAKER": "休闲户外防风衣外套",
            "TRAINING_PANTS": "休闲长裤",
            "TRAINING_POLO/SS": "POLO 短袖T恤",
            "TRAINING_SHORTS": "休闲短裤",
            "TRAINING_SOCKS": "袜子",
            "TRAINING_SWEATSHIRTS": "休闲套头衫",
            "TRAINING_TANK": "运动背心",
            "TRAINING_TEE/LS": "休闲长袖T恤",
            "TRAINING_TEE/SS": "休闲短袖T恤",
            "TRAINING_TIGHTS": "紧身裤打底裤",
            "TRAINING_OTHERS": "其他配饰",
            "CLASSIC_POLO/LS": "POLO 短袖T恤",
            "RUNNING_BAG": "包",
            "Training_BACKPACK": "包",
            "TRAINING_SHOE BAG": "包",
            "TRAINING_BACKPACK": "包",
            "CLASSIC_BACKPACK": "包",
            "CLASSIC_HAT": "其他配饰",
            "TRAINING_TOWEL": "其他配饰",
            "RUNNING_HAT": "其他配饰",
            "RUNNING_GLOVES": "其他配饰",
            "Training_HEADBAND": "其他配饰",
            "TRAINING_WRISTBAND": "其他配饰",
            "CLASSIC_TOWEL": "其他配饰",
            "CLASSIC_Hat": "其他配饰",
            "CLASSIC_OTHERS": "其他配饰",
            "TRAINING_APPAREL OTHERS": "其他配饰",
            "Training_SUITS": "套装",
            "TRAINING_SUITS": "套装",
            "TRAINING_SKIRTS": "休闲半裙",
            "RUNNING_VEST": "休闲背心外套",
            "TRAINING_VEST": "休闲背心外套",
            "RUNNING_JKT/WINDBREAKER": "休闲户外防风衣外套",
            "CLASSIC_TRACK TOP": "休闲夹克外套",
            "TRAINING_TRACK TOP": "休闲夹克外套",
            "Training_TRACK TOP": "休闲夹克外套",
            "Running_SHIRTS": "休闲套头衫",
            "Training_SHIRTS": "休闲套头衫",
            "TRAINING_SHIRTS": "休闲套头衫",
            "RUNNING_SWEATSHIRTS": "休闲套头衫",
            "TRAINING_VEST/DOWN": "休闲羽绒背心外套",
            "Training_CL JOGGER INFANTS": "休闲长裤",
            "TRAINING_3/4 PANTS": "休闲长裤",
            "CLASSIC_3/4 PANTS": "休闲长裤"
        }
    }

]

if __name__ == '__main__':
    from common.tool import CommonTool, ExcelTool

    v = CommonTool.get_matchvalue_from_dict(dictname='schema_ftw', keyword='Forever Floatride GROW', rulelist=rulelist,
                                            ignoreCase=True)
    print(v)

    print('Forever Floatride GROW'.find('FLOATRIDE'))

    # str1 = 'hello world'
    #
    # print(str1.title())  # Hello World
    # print(str1.swapcase())  # 转换大小写
    # print('STs'.swapcase())
    #
    # print(str1.capitalize())  # Hello world
    # print(str1.upper())  # Hello world
    # print('2F试试str1'.upper())  # Hello world
    # print('xFs'.lower())
    excel = ExcelTool('../../files/REEBOK类目标题转换规则.xlsx')
    import json

    print(json.dumps(excel.merge_dict('OTHER', 'xxx', '1,2', 4)))
